// <auto-generated />
using BlazorCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCRUD.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230509061425_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BlazorCRUD.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is some example content for post1.",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is some example content for post2.",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is some example content for post3.",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "This is some example content for post4.",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "This is some example content for post5.",
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "This is some example content for post6.",
                            Title = "Post 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "This is some example content for post7.",
                            Title = "Post 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "This is some example content for post8.",
                            Title = "Post 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "This is some example content for post9.",
                            Title = "Post 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "This is some example content for post10.",
                            Title = "Post 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
